#!/usr/bin/env php
<?php

declare(strict_types=1);

use Intisari\Application;

require __DIR__ . '/vendor/autoload.php';

$app = require __DIR__ . '/bootstrap/app.php';

assert($app instanceof Application);

require __DIR__ . '/routes/console.php';

exit($app->runConsole());
