#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$app = require __DIR__ . '/bootstrap/app.php';

if (is_file(__DIR__ . '/routes/console.php')) {
    require __DIR__ . '/routes/console.php';
}

exit($app->runConsole());
