name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate Composer
        run: composer validate --strict

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Source Integrity
        run: composer source:check

      - name: Run Tests
        run: composer test

      - name: Check Docs
        run: composer docs:check
